# Joint Limits for ABB IRB 120
# Values must match URDF and Datasheet

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 4.363  # 250 deg/s
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -2.879 # -165 deg
    max_position: 2.879  # +165 deg

  joint_2:
    has_velocity_limits: true
    max_velocity: 4.363
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -1.919 # -110 deg
    max_position: 1.919  # +110 deg

  joint_3:
    has_velocity_limits: true
    max_velocity: 4.363
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_position_limits: true
    min_position: -1.919 # -110 deg
    max_position: 1.221  # +70 deg

  joint_4:
    has_velocity_limits: true
    max_velocity: 5.585  # 320 deg/s
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_position_limits: true
    min_position: -2.792 # -160 deg
    max_position: 2.792  # +160 deg

  joint_5:
    has_velocity_limits: true
    max_velocity: 5.585
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_position_limits: true
    min_position: -2.094 # -120 deg
    max_position: 2.094  # +120 deg

  joint_6:
    has_velocity_limits: true
    max_velocity: 8.028  # 460 deg/s
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_position_limits: true
    min_position: -6.981 # -400 deg
    max_position: 6.981  # +400 deg
